/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastrarRouteImport } from './routes/cadastrar'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as MeusAgendamentosRouteImport } from './routes/meus-agendamentos'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAgendamentosRouteImport } from './routes/app.agendamentos'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppRelatorioRouteImport } from './routes/app.relatorio'
import { Route as AppServicosRouteImport } from './routes/app.servicos'
import { Route as PSlugRouteImport } from './routes/p.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRoute = CadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusAgendamentosRoute = MeusAgendamentosRouteImport.update({
  id: '/meus-agendamentos',
  path: '/meus-agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgendamentosRoute = AppAgendamentosRouteImport.update({
  id: '/app/agendamentos',
  path: '/app/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/app/clientes',
  path: '/app/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/app/configuracoes',
  path: '/app/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatorioRoute = AppRelatorioRouteImport.update({
  id: '/app/relatorio',
  path: '/app/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServicosRoute = AppServicosRouteImport.update({
  id: '/app/servicos',
  path: '/app/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/entrar': typeof EntrarRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/relatorio': typeof AppRelatorioRoute
  '/app/servicos': typeof AppServicosRoute
  '/p/$slug': typeof PSlugRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/entrar': typeof EntrarRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/relatorio': typeof AppRelatorioRoute
  '/app/servicos': typeof AppServicosRoute
  '/p/$slug': typeof PSlugRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/entrar': typeof EntrarRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/relatorio': typeof AppRelatorioRoute
  '/app/servicos': typeof AppServicosRoute
  '/p/$slug': typeof PSlugRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastrar'
    | '/entrar'
    | '/meus-agendamentos'
    | '/app/agendamentos'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/relatorio'
    | '/app/servicos'
    | '/p/$slug'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastrar'
    | '/entrar'
    | '/meus-agendamentos'
    | '/app/agendamentos'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/relatorio'
    | '/app/servicos'
    | '/p/$slug'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/cadastrar'
    | '/entrar'
    | '/meus-agendamentos'
    | '/app/agendamentos'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/relatorio'
    | '/app/servicos'
    | '/p/$slug'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrarRoute: typeof CadastrarRoute
  EntrarRoute: typeof EntrarRoute
  MeusAgendamentosRoute: typeof MeusAgendamentosRoute
  AppAgendamentosRoute: typeof AppAgendamentosRoute
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppRelatorioRoute: typeof AppRelatorioRoute
  AppServicosRoute: typeof AppServicosRoute
  PSlugRoute: typeof PSlugRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar': {
      id: '/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof CadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-agendamentos': {
      id: '/meus-agendamentos'
      path: '/meus-agendamentos'
      fullPath: '/meus-agendamentos'
      preLoaderRoute: typeof MeusAgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agendamentos': {
      id: '/app/agendamentos'
      path: '/app/agendamentos'
      fullPath: '/app/agendamentos'
      preLoaderRoute: typeof AppAgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/app/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/app/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/relatorio': {
      id: '/app/relatorio'
      path: '/app/relatorio'
      fullPath: '/app/relatorio'
      preLoaderRoute: typeof AppRelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/servicos': {
      id: '/app/servicos'
      path: '/app/servicos'
      fullPath: '/app/servicos'
      preLoaderRoute: typeof AppServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrarRoute: CadastrarRoute,
  EntrarRoute: EntrarRoute,
  MeusAgendamentosRoute: MeusAgendamentosRoute,
  AppAgendamentosRoute: AppAgendamentosRoute,
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppRelatorioRoute: AppRelatorioRoute,
  AppServicosRoute: AppServicosRoute,
  PSlugRoute: PSlugRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
