// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://sjxlludhozmojihuqxby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqeGxsdWRob3ptb2ppaHVxeGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUyODUxMDEsImV4cCI6MjEwMDg2MTEwMX0.TE7eKVUw7yPSzrZddOlvpCi3p0FxtN2TwYyrYxOSCjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
